### ISSUE TITLE
S30: admin-profile-edit

### ISSUE THREAD

**Issue by zeke13210** [zCode-Solutions/meetMyTypes#12]
As an admin, I would like the ability to modify a users record in order to update their profile after finishing zodiac analysis

Acceptance Criteria
1. Show all users with empty profiles
2. Allow edit of the below properties to the profile
- User love-type
- top 4 types
- Core personality profile
3. After saving record, user disappears from list and user receives email notification profile has been updated

Tasks
- [x] Determine parameters to be passed to the edit page component

- [x]  Gain access to dynamo db

- [ ]  Perform db query and update component

- [ ] Update table on submit

**Comment by nsawit** [comment]
hi @zeke13210 ,
Not sure on this, i'm thinking about from which page can we access the edit profile page?
I'm thinking of the below scenarios:
1. From "New users" page, admin clicks user name then the page will be redirected to edit profile page
2. From "Current users" page, clicking user profile pic / name will redirect the page to edit profile page

**Comment by MatthewChickoree** [comment]
Hi Nate/Zeke,

What is the new users page? Is this where a user signs up/registers?

Or a page with newly registered users who are awaiting admin approval?and

Admin should only edit registered users or should an admin also
add/register new users?


Best regards
Matthew

**Comment by nsawit** [comment]
@MatthewChickoree ,
I think new users page is where thenewly registered users are displayed.

The page where a user signs up is done in mobile app I think. 

cc @zeke13210

**Comment by zeke13210** [comment]
@nsawit to answer your first comment the admin will be able to reach the edit profile from both "new users" and "current users" it'll all route to the same component and allow them to update their info if needed.

@MatthewChickoree to answer your question @nsawit is correct the signup is coming from the mobile app and for the admin "new users" screen appear the newly registered users waiting for admin approval. The admin will have no ability to add newly registered users.

**Comment by MatthewChickoree** [comment]
Noted with thanks guys.

Best regards
Matthew

**Comment by nsawit** [comment]
JS
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.JavaScript.html

NodeJS
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html

**Comment by zeke13210** [comment]
feature ready for testing will close until new test case comes up
