### ISSUE TITLE
[BUG] Access to api blocked by CORS policy

### ISSUE THREAD

**Issue by nsawit** [zCode-Solutions/meetMyTypes#20]
**Describe the bug**
When navigating to the 'Current Users' page, user names are not loaded due to CORS policy issue. Access to the api https://qj87hoxzmk.execute-api.us-east-1.amazonaws.com/Dev/currentUsers is blocked by the CORS policy

**To Reproduce**
1. Just go to 'Current Users' page 

**Expected behavior**
User names should be displayed in the page

**Screenshots**
![image](https://user-images.githubusercontent.com/16936796/74121524-cfe8af80-4c02-11ea-8f58-3e89962d8a6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by zeke13210** [comment]
Resolved issue by modifying the AUTH setting within API gateway.
