### ISSUE TITLE
[BUG] Top 4 love types are not highlighted when loading user's profile

### ISSUE THREAD

**Issue by nsawit** [zCode-Solutions/meetMyTypes#21]
**Describe the bug**
When loading user's profile, their top 4 love types are not highlighted in the dropdown

**To Reproduce**
1. Go to 'Current Users' page
2. Click on user name then the Edit profile page will be shown
3. From the edit profile page, verify user's top 4 love types

**Expected behavior**
Top 4 love types should be highlighted in the Top 4 Love Types dropdown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by zeke13210** [comment]
will revisit once UI is finialized
