### ISSUE TITLE
S31: admin-user-search

### ISSUE THREAD

**Issue by zeke13210** [zCode-Solutions/meetMyTypes#6]
As an admin I would like the ability to search for a user by email address in order to quickly modify and update the users profile.

Acceptance Criteria
1. Search bar at top of user list
2. After entering email address and hitting search list filters to appropriate email addresses.

Tasks:
- [ ] Ramp-up ReactJS to build search functionality

- [ ] Pre-existing search template in React JS?

- [ ] Determine signature
- [ ] Determine parameters

**Comment by MatthewChickoree** [comment]
- [ ] Ramp-up ReactJS to build search functionality

- [ ] Pre-existing search template in React JS?

- [ ] Ramp-up Dynamo DB Query for searching

- [ ] Determine signature
- [ ] Determine parameters

**Comment by MatthewChickoree** [comment]
Dynamo DB resources: https://aws.amazon.com/dynamodb/getting-started/

**Comment by MatthewChickoree** [comment]
To validate that a Cognito user pool will be used for end users as well as admin users.

Can use the following Cognito API to search for user email.

Have to build the function in ReactJS with appropriate parameters etc: authentication for admin user to search another user pool.

https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-manage-user-accounts.html

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#listUsers-property

**Comment by zeke13210** [comment]
I like the idea go ahead and proceed with utilizing cognito API to pull in the data and creat the admin user pool in within N virgina location for cognito

**Comment by zeke13210** [comment]
issue completed with recent PR
